# ------------------------------------------------------------
# .github/labeler.yml
# Purpose:
#   - PR の変更ファイルパスに応じて自動ラベル付与
# Notes:
#   - actions/labeler@v5 形式（changed-files / any-glob-to-any-file）
# ------------------------------------------------------------

# =========================================================
# 翻訳対象のラベル
# =========================================================
Translation:
  - changed-files:
      any-glob-to-any-file:
        - "DCSWorld/**/*"

Aircrafts:
  - changed-files:
      any-glob-to-any-file:
        - "DCSWorld/Mods/aircraft/**/*"

"DLC Campaigns":
  - changed-files:
      any-glob-to-any-file:
        - "DCSWorld/Mods/campaigns/**/*"

# =========================================================
# リポジトリ管理用のラベル
# =========================================================
Infrastructure:
  - changed-files:
      any-glob-to-any-file:
        - '**'
        - '!DCSWorld/**'

Pages:
  - changed-files:
      any-glob-to-any-file:
        - 'docs/**'

Docs:
  - changed-files:
      any-glob-to-any-file:
        - 'README.md'
        - 'LICENSE'
        - '.github/CODE_OF_CONDUCT.md'
        - '.github/CONTRIBUTING.md'
        - '.github/PULL_REQUEST_TEMPLATE.md'
        - '.github/SECURITY.md'
        - '.github/ISSUE_TEMPLATE/**'

"CI / GitHub Actions":
  - changed-files:
      any-glob-to-any-file:
        - '.github/workflows/**'
        - '.github/labeler.yml'
