name: Release Mods as ZIP

on:
  release:
    types: [created]

jobs:
    zip-and-upload:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Create aircraft ZIP files
          run: |
            mkdir -p zips
            for dir in DCSWorld/Mods/aircraft/*/; do
              name=$(basename "$dir")
              zip -r "zips/${name}.zip" "$dir" -x '*.DS_Store' -x '__MACOSX/*' -x '*/Thumbs.db' -x '*/desktop.ini' -x '*.gitkeep'
            done

        - name: Create campaign ZIP files
          run: |
            mkdir -p zips
            for dir in DCSWorld/Mods/campaigns/*/; do
              name=$(basename "$dir")
              zip -r "zips/${name}.zip" "$dir" -x '*.DS_Store' -x '__MACOSX/*' -x '*/Thumbs.db' -x '*/desktop.ini' -x '*.gitkeep'
            done

        - name: Create tech ZIP files
          run: |
            mkdir -p zips
            for dir in DCSWorld/Mods/tech/*/; do
              name=$(basename "$dir")
              zip -r "zips/${name}.zip" "$dir" -x '*.DS_Store' -x '__MACOSX/*' -x '*/Thumbs.db' -x '*/desktop.ini' -x '*.gitkeep'
            done

        - name: Create terrains ZIP files
          run: |
            mkdir -p zips
            for dir in DCSWorld/Mods/terrains/*/; do
              name=$(basename "$dir")
              zip -r "zips/${name}.zip" "$dir" -x '*.DS_Store' -x '__MACOSX/*' -x '*/Thumbs.db' -x '*/desktop.ini' -x '*.gitkeep'
            done

        - name: Upload ZIPs to release
          uses: softprops/action-gh-release@v1
          with:
            files: zips/*.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
