name: Release Mods as ZIP

on:
  release:
    types: [created]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP files
        run: |
          mkdir -p zips

          for base in DCSWorld/Mods/aircraft DCSWorld/Mods/tech; do
            if [ -d "$base" ]; then
              subdirs=$(find "$base" -mindepth 1 -maxdepth 1 -type d)

              if [ -n "$subdirs" ]; then
                echo "Processing directories in $base"
                for dir in $subdirs; do
                  name=$(basename "$dir")
                  zip -r "zips/${name}.zip" "$dir" -x '*.DS_Store' -x '*.gitkeep' -x '*/Thumbs.db' -x '*/desktop.ini'
                done
              else
                echo "No subdirectories in $base (or only .gitkeep). Skipping."
              fi
            else
              echo "$base does not exist. Skipping."
            fi
          done


      - name: Upload ZIPs to release
        uses: softprops/action-gh-release@v1
        with:
          files: zips/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
