name: Release on Merge or Commit to master

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Release の作成に必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag name from date
        id: commit
        run: |
          echo "tag_name=$(date +v%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create ZIP files
        run: |
          mkdir -p zips

          for base in DCSWorld/Mods/aircraft DCSWorld/Mods/campaigns  DCSWorld/Mods/tech  DCSWorld/Mods/terrains; do
            if [ -d "$base" ]; then
              subdirs=$(find "$base" -mindepth 1 -maxdepth 1 -type d)

              if [ -n "$subdirs" ]; then
                echo "Processing directories in $base"
                for dir in $subdirs; do
                  name=$(basename "$dir")
                  zip -r "zips/${name}.zip" "$dir" \
                    -x '*.DS_Store' \
                    -x '*.gitkeep' \
                    -x '*/Thumbs.db' \
                    -x '*/desktop.ini'
                done
              else
                echo "No valid subdirectories in $base. Skipping."
              fi
            else
              echo "$base does not exist. Skipping."
            fi
          done

      - name: Collect Guides
        run: |
          mkdir -p extras
          if compgen -G "Guides/*.pdf" > /dev/null; then
            cp Guides/*.pdf extras/
          else
            echo "No PDF files found in Guides/"
          fi

      - name: Create GitHub Release with ZIPs and PDFs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ steps.commit.outputs.tag_name }}

          files=""
          for f in zips/*.zip extras/*.pdf; do
            if [ -e "$f" ]; then
              files="$files $f"
            fi
          done

          gh release create "$tag" $files \
            --title "Auto Release $tag" \
            --notes "This release was automatically generated on push to master."