name: Release on Merge to main

on:
  push:
    branches:
      - main  # ← mainにマージされたときに発火

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # リリース作成に必要

    steps:
      - uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v1

      - name: Get latest commit info
        id: commit
        run: |
          echo "tag_name=$(date +v%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create ZIP files
        run: |
          mkdir -p zips

          for base in DCSWorld/Mods/aircraft DCSWorld/Mods/tech; do
            if [ -d "$base" ]; then
              subdirs=$(find "$base" -mindepth 1 -maxdepth 1 -type d)

              if [ -n "$subdirs" ]; then
                echo "Processing directories in $base"
                for dir in $subdirs; do
                  name=$(basename "$dir")
                  zip -r "zips/${name}.zip" "$dir" -x '*.DS_Store' -x '*.gitkeep' -x '*/Thumbs.db' -x '*/desktop.ini'
                done
              else
                echo "No subdirectories in $base (or only .gitkeep). Skipping."
              fi
            else
              echo "$base does not exist. Skipping."
            fi
          done

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ steps.commit.outputs.tag_name }}
          gh release create "$tag" zips/*.zip \
            --title "Auto Release $tag" \
            --notes "This release was automatically generated on merge to main."
