name: Release on Merge or Commit to master

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag name from date
        id: commit
        run: |
          echo "tag_name=$(date +v%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create ZIP files
        run: |
          target_dir="DCSWorld/Mods/aircraft"
          output_dir="zips/aircraft"

          mkdir -p "$output_dir"

          target_dir="DCSWorld/Mods/aircraft"

          for dir in "$target_dir"/*/ ; do
            [ -d "$dir" ] || continue
            echo "${dir}"
            tmpdir=$(mktmp -d)
            aircraft_model=$(basename "$dir")

            subdir="${dir}/Missions/Single"
            if [ -d "${subdir}" ]; then
              for mission_file in "${subdir}/*/]" ; do
                echo "${mission_file}"
                mkdir -p "${tmpdir}/${aircraft_model}/Missions/Single"
                zip -r -0 "${tmpdir}/${aircraft_model}/Missions/Single" "${mission_file}"
              done
            else
              echo "Skip. ${subdir} does not exist"
            fi

            zip -r -0 "${output_dir}/${aircraft_model}.zip" "${tmpdir}/${aircraft_model}"
          done

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ steps.commit.outputs.tag_name }}
          gh release create "$tag" --title "Auto Release $tag"

      - name: Upload ZIPs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ steps.commit.outputs.tag_name }}
          find zips extras -type f -print0 | while IFS= read -r -d '' file; do
            echo "Uploading: $file"
            gh release upload "$tag" "$file" --clobber
          done
